# Generated by Django 6.0.5 on 2026-05-30 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('comunidade_snmp', models.CharField(default='public', max_length=100)),
                ('versao_snmp', models.CharField(choices=[('1', 'v1'), ('2c', 'v2c'), ('3', 'v3')], default='2c', max_length=3)),
                ('oid_contador', models.CharField(default='1.3.6.1.2.1.43.10.2.1.4.1.1', max_length=200)),
                ('oid_toner', models.CharField(blank=True, max_length=200)),
                ('custo_por_pagina', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('franquia_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LeituraContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_contador', models.BigIntegerField()),
                ('nivel_toner', models.IntegerField(blank=True, null=True)),
                ('manual', models.BooleanField(default=False)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='impressoras.impressora')),
            ],
            options={
                'verbose_name': 'Leitura de Contador',
                'verbose_name_plural': 'Leituras de Contadores',
                'ordering': ['-lido_em'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('contador_inicial', models.BigIntegerField(default=0)),
                ('contador_final', models.BigIntegerField(default=0)),
                ('paginas_impressas', models.BigIntegerField(default=0)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='impressoras.impressora')),
            ],
            options={
                'verbose_name': 'Relatório Mensal',
                'verbose_name_plural': 'Relatórios Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('impressora', 'ano', 'mes')},
            },
        ),
    ]
