# Generated by Django 6.0.5 on 2026-05-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('todas', models.BooleanField(default=False)),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária (horário fixo)'), ('intervalo', 'A cada X minutos')], default='diaria', max_length=20)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('intervalo_minutos', models.PositiveIntegerField(default=60)),
                ('ativo', models.BooleanField(default=True)),
                ('proxima_execucao', models.DateTimeField()),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('impressora', models.ForeignKey(blank=True, help_text='Deixe em branco para coletar todas as impressoras', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='impressoras.impressora')),
            ],
            options={
                'verbose_name': 'Agendamento de Coleta',
                'verbose_name_plural': 'Agendamentos de Coleta',
                'ordering': ['proxima_execucao'],
            },
        ),
    ]
