# Generated by Django 6.0.5 on 2026-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0002_agendamento_coleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='entidade',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
