# Generated by Django 6.0.5 on 2026-06-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0003_add_entidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Toner', max_length=50)),
                ('cor', models.CharField(choices=[('K', 'Preto'), ('C', 'Ciano'), ('M', 'Magenta'), ('Y', 'Amarelo'), ('O', 'Outro')], default='K', max_length=1)),
                ('oid', models.CharField(max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toners', to='impressoras.impressora')),
            ],
            options={
                'verbose_name': 'Configuração de Toner',
                'verbose_name_plural': 'Configurações de Toner',
                'ordering': ['ordem', 'cor'],
            },
        ),
        migrations.CreateModel(
            name='LeituraToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=1)),
                ('nivel', models.IntegerField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toners', to='impressoras.leituracontador')),
                ('toner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impressoras.tonerconfig')),
            ],
            options={
                'verbose_name': 'Leitura de Toner',
                'verbose_name_plural': 'Leituras de Toner',
                'ordering': ['ordem', 'cor'],
            },
        ),
    ]
