# Generated by Django 6.0.5 on 2026-06-01 12:45

from django.db import migrations


def oid_toner_para_tonerconfig(apps, schema_editor):
    Impressora = apps.get_model('impressoras', 'Impressora')
    TonerConfig = apps.get_model('impressoras', 'TonerConfig')
    for imp in Impressora.objects.exclude(oid_toner=''):
        if not TonerConfig.objects.filter(impressora=imp).exists():
            TonerConfig.objects.create(
                impressora=imp,
                nome='Toner',
                cor='K',
                oid=imp.oid_toner,
                ordem=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0004_add_toner_models'),
    ]

    operations = [
        migrations.RunPython(oid_toner_para_tonerconfig, migrations.RunPython.noop),
    ]
