# Generated by Django 6.0.5 on 2026-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0005_migrate_oid_toner_to_tonerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituracontador',
            name='status_hw',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
